/* Wattlings · jeu/recit/lieux-savoir.js
   Où se trouvent les informations en ville : chaque source est un personnage ou un objet, avec sa réplique. */

/* ================= FICHES SAVOIR : l'Essentiel du cours, éparpillé dans la ville ================= */
/* Lieux : chaque source est un personnage ou un objet. ins = bâtiment où elle se trouve (null = dehors). */
const SRC={
  geometre:{map:'town',x:60,y:21,kind:'npc',who:'Géomètre',pal:{skin:'#c68a5c',shirt:'#e2a13a',pants:'#5b6380',hair:'#2b1d14',hat:'#f7f0dc',hatType:'helmet',vest:1,prop:'plan'},dir:'down',where:'le géomètre, au Puy du Cadastre (au nord de la place)',idle:["Je mesure tout. Même la patience des gens qui me demandent de me pousser."]},
  planquartier:{map:'town',x:59,y:21,kind:'sign',who:null,where:'le plan de quartier, au Puy du Cadastre',idle:["Plan de quartier d’Ampère-sur-Loire. Quelqu’un a entouré la piscine en rouge et écrit « gouffre ? »."]},
  agentEnedis:{map:'town',x:70,y:21,kind:'npc',existing:1,who:'Agent Enedis',where:'l’agent Enedis, au Puy du Cadastre'},
  officeObj:{map:'office',x:4,y:1,kind:'poster',who:null,where:'l’affiche des objectifs, dans ton bureau',idle:["« Objectifs énergie » : une affiche. Quelqu’un a ajouté au feutre : « et arrêter de chauffer le parking »."]},
  cycle:{map:'office',x:8,y:1,kind:'poster',who:null,where:'l’affiche du cycle, dans ton bureau',idle:["L’affiche du cycle en 8 étapes. Elle tourne en rond, comme les réunions."]},
  drOhm:{ins:'cabinet',x:5,y:3,kind:'npc',who:'Dr Ohm',pal:{skin:'#f6d3b3',shirt:'#8ec9e8',pants:'#6d7896',coat:'#f7f0dc',hair:'#ece6d6',glasses:1,stetho:1},dir:'down',where:'le Dr Ohm, au cabinet médical (Puy du Cadastre)',idle:["Je soigne les gens et, à mes heures perdues, les bâtiments. Les bâtiments se plaignent moins."]},
  ecg:{map:'town',x:27,y:61,kind:'sign',who:null,where:'le panneau du parcours santé, au parc des Courbes',idle:["Panneau du parcours santé : un électrocardiogramme géant. Le tracé ressemble étrangement à une courbe de charge."]},
  conseillere:{ins:'enedis',x:5,y:3,kind:'npc',who:'Conseillère Enedis',pal:{skin:'#9a6440',shirt:'#f7f0dc',pants:'#2c2c34',jacket:'#2f6db5',hair:'#2b1d14',style:'long',lash:1,scarf:'#f2c12e',prop:'tablet'},dir:'down',where:'la conseillère de l’agence Enedis (Cité des Beffrois)',idle:["Bienvenue chez Enedis. Pour une réclamation, prenez un ticket. Pour une donnée, prenez un mandat."]},
  electricien:{ins:'enedis',x:2,y:4,kind:'npc',who:'Électricien',pal:{skin:'#e0ac7e',shirt:'#e2a13a',pants:'#2f3a5c',hair:'#2b1d14',hat:'#f2c12e',hatType:'helmet',vest:1,beard:'#2b1d14',prop:'wrench'},dir:'right',where:'l’électricien, à l’agence Enedis',idle:["J’ai vu des compteurs afficher des choses… Des choses que tu n’imagines pas."]},
  depassement:{ins:'enedis',x:8,y:1,kind:'poster',who:null,where:'l’affiche des dérives, à l’agence Enedis',idle:["Affiche : « Votre talon monte ? Ce n’est pas la faute du compteur. (Enfin, rarement.) »"]},
  techGRDF:{ins:'grdf',x:5,y:3,kind:'npc',who:'Technicienne GRDF',pal:{skin:'#f1c7a1',shirt:'#e2573b',pants:'#333',overall:'#1c7a9a',hair:'#5a3a22',style:'queue',hat:'#1c6fb3',hatType:'cap',lash:1,prop:'wrench'},dir:'down',where:'la technicienne du poste GRDF (Cité des Beffrois)',idle:["Le gaz, c’est simple : ça arrive en m³, ça se facture en kWh, et entre les deux il y a un coefficient que tout le monde oublie."]},
  convGRDF:{ins:'grdf',x:3,y:1,kind:'poster',who:null,where:'l’affiche de conversion, au poste GRDF',idle:["Affiche : « 1 m³ de gaz ≈ 11 kWh. Environ. Selon la commune. Et le mois. Et l’humeur du PCS. »"]},
  retraite:{map:'town',x:76,y:43,kind:'npc',existing:1,who:'Retraité',where:'le retraité, à la Cité des Beffrois'},
  conseiller:{ins:'voltco',x:5,y:3,kind:'npc',who:'Conseiller Volt&Co',pal:{skin:'#f6d3b3',shirt:'#f7f0dc',pants:'#333',jacket:'#c43d3d',hair:'#2b1d14',tie:'#f2a33a',prop:'case'},dir:'down',where:'le conseiller de Volt&Co, le fournisseur (Cité des Beffrois)',idle:["Chez Volt&Co, nos prix sont transparents. Tellement transparents qu’on ne les voit pas."]},
  dab:{map:'town',x:80,y:31,kind:'dab',who:null,where:'le distributeur de billets, à la Cité des Beffrois',idle:["Distributeur de billets. « Solde : suffisant pour un café, pas pour une chaudière. »"]},
  tech:{map:'town',existing:1,who:'Technicien',where:'le technicien, à l’entrée du Parc des Données (Clos du Tamis)'},
  panneauParc:{map:'town',x:77,y:60,kind:'sign',who:null,where:'le panneau des contrôles, devant le Parc des Données (Clos du Tamis)',idle:["Panneau du Parc : « Contrôles quotidiens. Les données qui ne passent pas sont priées de patienter à l’accueil. »"]},
  lecteur:{ins:'media',x:8,y:5,kind:'npc',who:'Archiviste',pal:{skin:'#f1c7a1',shirt:'#6d7896',pants:'#2c2c34',jacket:'#59627c',hair:'#9a9aa2',style:'carre',glasses:1,prop:'book'},dir:'left',where:'l’archiviste, à la médiathèque',idle:["Chut. On est dans une médiathèque. Même les données chuchotent."]},
  biblio:{ins:'media',x:5,y:3,kind:'npc',who:'Bibliothécaire',pal:{skin:'#f6d3b3',shirt:'#2f9e7a',pants:'#6b4a2b',skirt:1,hair:'#b8431f',bun:1,glasses:1,lash:1,prop:'book'},dir:'down',where:'la bibliothécaire, à la médiathèque (Quartier des Colombages)',idle:["Tout a une place. Sauf les fichiers Excel nommés « final_v2 ». Ceux-là, on les brûle."]},
  borne:{ins:'media',x:2,y:2,kind:'borne',who:'Borne de prêt',where:'la borne de prêt, à la médiathèque (Quartier des Colombages)',idle:["La borne affiche : « Aucun emprunt en cours. Retards : 0. Félicitations, c’est rare. »"]},
  rayonStat:{ins:'media',x:8,y:2,kind:'shelf',who:null,where:'le rayon Statistiques, à la médiathèque',idle:["Rayon Statistiques. Un livre s’intitule « 101 façons de mentir avec une moyenne »."]},
  rayonRegl:{ins:'media',x:9,y:2,kind:'shelf',who:null,where:'le rayon Réglementation, à la médiathèque',idle:["Rayon Réglementation. Les livres sont rangés par date d’abrogation."]},
  horloge:{map:'town',x:60,y:61,kind:'clock',who:null,where:'l’horloge du jardin, au Quartier des Colombages',idle:["L’horloge du jardin. Elle avance de 10 minutes. Ou plutôt : elle compte par pas de 10 minutes."]},
  gardien:{map:'town',x:65,y:33,kind:'npc',who:'Gardien de l’école',pal:{skin:'#6b4128',shirt:'#5b6380',pants:'#2c2c34',hair:'#2b1d14',hat:'#2c2c34',hatType:'cap',prop:'broom'},dir:'left',where:'le gardien, devant l’école',idle:["Je ferme l’école à 18 h. Le bâtiment, lui, ne s’en rend jamais compte."]},
  meteo:{map:'town',x:37,y:63,kind:'npc',who:'Météorologue',pal:{skin:'#f1c7a1',shirt:'#1a73c9',pants:'#2c2c34',coat:'#f2c12e',hair:'#d9a441',style:'long',lash:1,prop:'umbrella'},dir:'left',where:'la météorologue, à la station météo (Coteaux des Courbes)',idle:["Demain : couvert, avec des éclaircies de sobriété en fin de journée."]},
  mat:{map:'town',x:34,y:19,kind:'mast',who:null,where:'le tableau du relais météo, à l’Alpage de la Preuve',idle:["Relais météo d’Ampère-sur-Loire. Température : de saison. Moral des chaudières : bon."]},
  veilleur:{map:'town',x:12,y:51,kind:'npc',who:'Veilleur de nuit',pal:{skin:'#c68a5c',shirt:'#2c2c34',pants:'#2c2c34',hair:'#5a3a22',hat:'#1c2440',hatType:'cap',beard:'#5a3a22',prop:'lantern'},dir:'down',when:()=>S.ch===7,where:'le veilleur de nuit, à l’Anse du Veilleur',idle:["La nuit, la ville dort. Les veilles, elles, ne dorment jamais."]},
  plombier:{map:'town',x:10,y:54,kind:'npc',who:'Plombier',pal:{skin:'#e0ac7e',shirt:'#f7f0dc',pants:'#2f6db5',overall:'#2f6db5',hair:'#2b1d14',hat:'#c43d3d',hatType:'cap',beard:'#2b1d14',prop:'wrench'},dir:'left',where:'le plombier, à l’Anse du Veilleur',idle:["Plombier. Je répare les fuites. Les vôtres sont en kWh ? Pas mon rayon, mais je compatis."]},
  artisan:{map:'town',x:14,y:19,kind:'npc',who:'Artisan',pal:{skin:'#f1c7a1',shirt:'#8a5a2b',pants:'#2f3a5c',apron:'#6b4a2b',hair:'#2b1d14',hat:'#e2a13a',hatType:'helmet',beard:'#5a3a22'},dir:'down',where:'l’artisan, près du parc solaire (Mas du Soleil)',idle:["Isolation, fenêtres, chaudières… Mais je vous préviens : isoler un bâtiment chauffé le week-end, c’est chauffer le vide avec style."]},
  installateur:{map:'town',x:8,y:17,kind:'npc',who:'Installatrice solaire',pal:{skin:'#9a6440',shirt:'#f2c12e',pants:'#2f3a5c',overall:'#333',hair:'#2b1d14',style:'queue',hat:'#f7f0dc',hatType:'helmet',lash:1,prop:'wrench'},dir:'up',where:'l’installatrice, au parc solaire (Mas du Soleil)',idle:["Mes panneaux produisent surtout l’été. Les écoles, elles, sont surtout fermées l’été. On y travaille."]},
  mmeDupuis:{ins:'maison',x:4,y:3,kind:'npc',who:'Mme Dupuis',pal:{skin:'#f1c7a1',shirt:'#e57399',pants:'#2f3a5c',skirt:1,apron:'#f7f0dc',hair:'#2b1d14',style:'long',lash:1},dir:'down',where:'Mme Dupuis, dans sa maison (Mas du Soleil)',idle:["Mon mari croit que le thermostat est un objet décoratif."]},
  mDupuis:{ins:'maison',x:7,y:4,kind:'npc',who:'M. Dupuis',pal:{skin:'#f6d3b3',shirt:'#2f9e7a',pants:'#6b4a2b',hair:'#9a9aa2',glasses:1,beard:'#9a9aa2',prop:'book'},dir:'left',where:'M. Dupuis, dans sa maison (Mas du Soleil)',idle:["J’ai acheté un thermostat connecté. Il me connecte surtout à ma banque."]},
  pharma:{ins:'pharma',x:5,y:3,kind:'npc',who:'Pharmacienne',pal:{skin:'#e0ac7e',shirt:'#2fbf5e',pants:'#2f6d34',coat:'#f7f0dc',hair:'#d9a441',bun:1,lash:1},dir:'down',where:'la pharmacienne (Alpage de la Preuve)',idle:["Pour les maux de tête dus aux factures d’énergie, j’ai du paracétamol. Pour la facture, rien."]},
  balance:{ins:'pharma',x:8,y:3,kind:'balance',who:'Balance',where:'la balance de la pharmacie',idle:["Une balance. Elle affiche « Pesez-vous toujours dans les mêmes conditions ». Elle sait des choses."]},
  maire:{map:'mairie',existing:1,who:'Maire',where:'le maire, à l’hôtel de ville'},
  posterMairie:{map:'mairie',x:5,y:1,kind:'poster',who:null,where:'l’affiche du Pareto, à l’hôtel de ville',idle:["Affiche : « 20 % des sites, 80 % des problèmes. 100 % des réunions. »"]},
  marchand:{map:'town',x:30,y:45,kind:'npc',who:'Marchand',pal:{skin:'#f1c7a1',shirt:'#f7f0dc',pants:'#6b4a2b',apron:'#2f6d34',hair:'#b8431f',hat:'#e3cf98',hatType:'straw',beard:'#b8431f'},dir:'down',where:'le marchand du marché, place de l’Énergie',idle:["Tomates, courgettes, et des conseils gratuits. Les conseils sont hors saison."]},
  joule:{map:'office',existing:1,who:'Mme Joule',where:'Mme Joule, dans ton bureau'}
};
/* Fiches : st = étape du cours, k = phrase / retenir / analogie, req = indispensable pour débloquer le mini-jeu de l'étape. */
