/**
 * Le glossaire : chaque terme, sa définition, un exemple et les étapes où il apparaît.
 * Dans les textes du cours, {{cle}} ou {{cle|texte affiché}} crée un lien vers le terme.
 * src : les sources de la définition (clés du registre commun/donnees/sources.js), affichées sous l'exemple.
 */
export const GLOSSAIRE = {
  puissance: {
    terme: "Puissance",
    def: "La vitesse à laquelle un appareil consomme de l'énergie à un instant donné. Elle se mesure en watts (W) ou kilowatts (kW).",
    ex: "À midi, avec la cuisine et toutes les classes allumées, l’école appelle environ 50 kW.",
    etapes: [2, 5],
  },
  energie: {
    terme: "Énergie",
    def: "La quantité totale consommée sur une durée. C'est la puissance multipliée par le temps, en kilowattheures (kWh).",
    ex: "Sur une année scolaire, l’école consomme environ 86 000 kWh d’électricité.",
    etapes: [2, 4],
  },
  kw: {
    terme: "kW",
    def: "Kilowatt : 1 000 watts. Unité de puissance, comme les km/h pour une voiture.",
    ex: "Le talon nocturne de l’école est d’environ 6 kW.",
    etapes: [2, 5],
  },
  kwh: {
    terme: "kWh",
    def: "Kilowattheure : l’énergie consommée par une puissance de 1 kW pendant 1 heure. C’est l’unité qu’on paie, comme les km parcourus.",
    ex: "Un radiateur de 2 kW allumé 3 heures consomme 6 kWh.",
    etapes: [2, 4],
  },
  kva: {
    terme: "kVA",
    def: "Kilovoltampère : unité de puissance « apparente », utilisée pour les contrats et le dimensionnement des réseaux. Elle est un peu supérieure à la puissance en kW (kW = kVA × cos φ).",
    ex: "L’école a souscrit 60 kVA, soit environ 56 kW utilisables.",
    etapes: [1, 5],
  },
  "courbe-de-charge": {
    terme: "Courbe de charge",
    def: "La suite des puissances moyennes mesurées à intervalle régulier. Elle montre comment la consommation évolue dans la journée.",
    ex: "Au pas de 10 minutes, la courbe de l’école compte 144 points par jour.",
    etapes: [2, 3, 5],
    src: ["enedis-nmo-cf-016e", "enedis-guide-flux-r6x"],
  },
  "pas-de-temps": {
    terme: "Pas de temps",
    def: "La durée entre deux mesures successives (10 min, 30 min, 1 h, 1 jour…). Plus il est court, plus la donnée est fine.",
    ex: "Le compteur électrique de l’école mesure au pas de 10 min, le gaz au pas journalier.",
    etapes: [2, 4],
  },
  index: {
    terme: "Index",
    def: "Le totalisateur du compteur, qui ne fait qu’augmenter. La consommation d’une période est l’index de fin moins l’index de début.",
    ex: "Index gaz au 1er nov. : 41 940 m³ ; au 1er déc. : 44 867 m³ ; consommation : 2 927 m³.",
    etapes: [2, 3],
    src: ["enedis-guide-flux-r6x", "mne-releve-compteur"],
  },
  cadran: {
    terme: "Cadran (poste)",
    def: "Un index séparé pour une plage horaire ou une saison. Un compteur multi-cadrans a plusieurs index ; la consommation totale est leur somme.",
    ex: "L’école a 4 postes : HPH, HCH, HPB, HCB.",
    etapes: [2, 4],
    src: ["enedis-guide-flux-r6x"],
  },
  "hp-hc": {
    terme: "Heures pleines / creuses",
    def: "Des plages horaires où le kWh est plus cher (pleines) ou moins cher (creuses). Combinées aux saisons haute (hiver) et basse, elles donnent les postes horosaisonniers.",
    ex: "Pour l’école (simplifié) : heures pleines de 6 h à 22 h du lundi au samedi, saison haute de novembre à mars.",
    etapes: [2],
    src: ["enedis-turpe7-brochure"],
  },
  bouclage: {
    terme: "Bouclage",
    def: "Quand l’index atteint sa valeur maximale, il repart à zéro, comme le compteur kilométrique d’une vieille voiture. Un calcul naïf donne alors une consommation négative.",
    ex: "Le compteur gaz a 5 chiffres : après 99 999 m³, il affiche 00 000.",
    etapes: [2, 3],
  },
  pdl: {
    terme: "PDL (ou PRM)",
    def: "Point De Livraison : l’identifiant à 14 chiffres d’un raccordement électrique chez Enedis. Il est aussi appelé PRM (Point de Référence Mesure).",
    ex: "PDL fictif de l’école : 30001234567890.",
    etapes: [1, 4],
    src: ["enedis-pdl"],
  },
  pce: {
    terme: "PCE",
    def: "Point de Comptage et d’Estimation : l’identifiant d’un point de livraison de gaz chez GRDF, en général 14 chiffres.",
    ex: "PCE fictif de l’école : 21456789012345.",
    etapes: [1, 4],
    src: ["grdf-guide-donnees-2026"],
  },
  "point-de-comptage": {
    terme: "Point de comptage",
    def: "L’endroit précis où l’énergie est mesurée. Un site peut en avoir plusieurs, et un compteur peut couvrir plusieurs usages.",
    ex: "L’école a deux points de comptage : un pour l’électricité, un pour le gaz.",
    etapes: [1],
  },
  distributeur: {
    terme: "Gestionnaire de réseau de distribution",
    def: "L’entreprise qui gère les câbles ou les tuyaux jusqu’au bâtiment, pose les compteurs et fournit les données de mesure. Il est unique pour une zone donnée.",
    ex: "Pour l’école : Enedis (électricité) et GRDF (gaz).",
    etapes: [1, 2],
    src: ["mne-acteurs-marche", "enedis-turpe7-brochure"],
  },
  fournisseur: {
    terme: "Fournisseur",
    def: "L’entreprise qui vend l’énergie et envoie la facture. On peut en changer sans changer de compteur ni de distributeur.",
    ex: "L’école reçoit ses factures d’un fournisseur choisi par la mairie, pas d’Enedis.",
    etapes: [2],
    src: ["mne-acteurs-marche", "mne-changer-fournisseur"],
  },
  telereleve: {
    terme: "Télérelevé",
    def: "Une mesure transmise automatiquement à distance par le compteur, sans passage d’un technicien.",
    ex: "Le compteur électrique de l’école envoie sa courbe de charge tous les jours.",
    etapes: [2],
    src: ["enedis-linky-facilite"],
  },
  linky: {
    terme: "Linky",
    def: "Le compteur électrique communicant d’Enedis pour les raccordements jusqu’à 36 kVA (logements, petits commerces).",
    ex: "L’école, à 60 kVA, n’a pas de Linky mais un compteur professionnel télérelevé.",
    etapes: [1, 2],
    src: ["enedis-segments-c1-c5", "mne-compteurs-communicants"],
  },
  c4: {
    terme: "Segment C4",
    def: "Les raccordements électriques en basse tension au-delà de 36 kVA : bâtiments tertiaires moyens, PME. Leurs compteurs sont télérelevés et mesurent une courbe de charge fine.",
    ex: "L’école est en C4 avec 60 kVA et 4 postes horosaisonniers.",
    etapes: [1, 2],
    src: ["enedis-segments-c1-c5", "enedis-nmo-cf-015e"],
  },
  gazpar: {
    terme: "Gazpar",
    def: "Le compteur de gaz communicant de GRDF. Il transmet chaque jour son index, d’où l’on déduit une consommation journalière.",
    ex: "Le Gazpar de l’école transmet ses données chaque jour ; la consommation d’un jour est visible 1 à 3 jours plus tard.",
    etapes: [1, 2],
    src: ["mne-compteurs-communicants", "grdf-adict-faq"],
  },
  pcs: {
    terme: "PCS",
    def: "Pouvoir Calorifique Supérieur : l’énergie contenue dans un m³ de gaz, en kWh, en comptant la chaleur récupérable de la vapeur d’eau.",
    ex: "Le gaz livré à l’école contient environ 11,2 kWh par m³.",
    etapes: [2, 4],
    src: ["mne-pcs", "sdes-chiffres-cles-2025"],
  },
  "coef-conversion": {
    terme: "Coefficient de conversion",
    def: "Le nombre de kWh par m³ appliqué pour convertir le volume de gaz en énergie. Il dépend du PCS et des conditions de livraison (altitude, pression), et varie selon la commune et le mois.",
    ex: "En janvier, 4 000 m³ × 11,2 = 44 800 kWh.",
    etapes: [2, 4],
    src: ["mne-coefficient-conversion", "grdf-coefficient-conversion"],
  },
  consentement: {
    terme: "Consentement",
    def: "L’accord du titulaire du contrat qui autorise un tiers à accéder à ses données de consommation, pour une durée et un périmètre donnés.",
    ex: "La mairie signe un consentement pour que l’EMS récupère la courbe de charge de l’école.",
    etapes: [2],
    src: ["enedis-nmo-cf-015e", "enedis-contrat-sge", "grdf-guide-donnees-2026"],
  },
  "tiers-autorise": {
    terme: "Tiers autorisé",
    def: "Une entreprise habilitée à récupérer les données d’un client auprès du distributeur, grâce au consentement de ce client.",
    ex: "L’éditeur de l’EMS est le tiers autorisé pour les compteurs de l’école.",
    etapes: [2],
    src: ["enedis-contrat-sge"],
  },
  rgpd: {
    terme: "RGPD",
    def: "Le règlement européen sur la protection des données personnelles. Une courbe de charge de logement révèle la vie des occupants : c’est une donnée personnelle.",
    ex: "Les données d’un bâtiment tertiaire comme l’école sont moins sensibles, mais l’accès reste encadré par le consentement.",
    etapes: [2],
    src: ["cnil-rgpd", "cnil-linky-courbe-de-charge", "cnil-donnee-personnelle", "enedis-nmo-cf-015e"],
  },
  turpe: {
    terme: "TURPE",
    def: "Tarif d’Utilisation des Réseaux Publics d’Électricité. Fixé par la CRE, il rémunère les réseaux et apparaît dans la ligne « acheminement ».",
    ex: "Sur la facture de l’école, le TURPE a une part fixe (liée aux 60 kVA) et une part par kWh.",
    etapes: [2, 7],
    src: ["enedis-turpe7-brochure", "enedis-facturation-acheminement"],
  },
  accise: {
    terme: "Accise",
    def: "Une taxe proportionnelle à la quantité d’énergie consommée (en €/MWh). Elle existe pour l’électricité et pour le gaz naturel, et son taux change régulièrement (à vérifier chaque année).",
    ex: "Pour l’école, la ligne « accise » est proportionnelle aux kWh du mois.",
    etapes: [2],
    src: ["ministere-guide-fiscalite-2026"],
  },
  cta: {
    terme: "CTA",
    def: "Contribution Tarifaire d’Acheminement : un pourcentage de la part fixe de l’acheminement, qui finance les retraites des agents des industries électriques et gazières.",
    ex: "Sur la facture de l’école, la CTA ne bouge pas quand la consommation baisse.",
    etapes: [2],
    src: ["ministere-guide-fiscalite-2026", "cnieg-cta-note"],
  },
  tva: {
    terme: "TVA",
    def: "La taxe sur la valeur ajoutée, appliquée à la fin de la facture. Pour un professionnel, elle est de 20 % sur tous les postes.",
    ex: "Pour une facture de 1 500 € HT, l’école paie 1 800 € TTC.",
    etapes: [2],
    src: ["ministere-guide-fiscalite-2026"],
  },
  abonnement: {
    terme: "Abonnement",
    def: "La part fixe de la facture, payée même sans rien consommer.",
    ex: "En août, école fermée, l’abonnement est dû quand même.",
    etapes: [2, 7],
    src: ["mne-elements-facture"],
  },
  fourniture: {
    terme: "Fourniture",
    def: "La part de la facture qui paie l’énergie elle-même, au prix fixé avec le fournisseur, pour chaque kWh consommé.",
    ex: "En janvier, la fourniture est la plus grosse ligne de la facture de gaz.",
    etapes: [2],
    src: ["mne-prix-pro"],
  },
  acheminement: {
    terme: "Acheminement",
    def: "La part de la facture qui paie le transport de l’énergie par les réseaux jusqu’au bâtiment (TURPE pour l’électricité, tarifs de distribution et de transport pour le gaz).",
    ex: "L’acheminement est reversé à Enedis et GRDF via le fournisseur.",
    etapes: [2],
    src: ["mne-prix-pro", "enedis-facturation-acheminement"],
  },
  "facture-estimee": {
    terme: "Facture estimée",
    def: "Une facture calculée sur une consommation supposée, faute de relevé réel.",
    ex: "La facture de gaz de janvier-février de l’école est estimée trop bas de 30 %.",
    etapes: [2, 3],
    src: ["mne-releve-compteur", "mne-frequence-facturation"],
  },
  regularisation: {
    terme: "Régularisation",
    def: "La correction, sur une facture suivante, de l’écart entre ce qui a été estimé et ce qui a été réellement consommé.",
    ex: "La facture de février-mars rattrape les 13 000 kWh sous-estimés.",
    etapes: [2, 3],
    src: ["mne-frequence-facturation"],
  },
  horodatage: {
    terme: "Horodatage",
    def: "La date et l’heure attachées à une mesure. Il faut savoir si elles désignent le début ou la fin de l’intervalle, et dans quel fuseau.",
    ex: "La mesure « 10:00 » de l’école couvre 10:00 à 10:10.",
    etapes: [3],
  },
  utc: {
    terme: "UTC",
    def: "Le temps universel, sans heure d’été ni d’hiver. La France est à UTC+1 en hiver et UTC+2 en été.",
    ex: "Stocker en UTC évite les journées de 23 h et 25 h.",
    etapes: [3],
  },
  interpolation: {
    terme: "Interpolation",
    def: "Estimer une valeur manquante à partir des valeurs voisines (par exemple une ligne droite entre la dernière valeur avant le trou et la première après).",
    ex: "Un trou de 30 min la nuit peut être interpolé sans risque ; un trou d’une journée, non.",
    etapes: [3],
  },
  "donnee-brute": {
    terme: "Donnée brute / corrigée / estimée",
    def: "Le statut d’une donnée : telle que reçue, modifiée par un contrôle, ou calculée faute de mesure. On garde toujours la trace du statut.",
    ex: "Le pic à 999,9 kW de l’école est marqué « brute, rejetée ».",
    etapes: [3],
  },
  agregation: {
    terme: "Agrégation",
    def: "Regrouper des données fines en données plus grossières : sommer des énergies, ou moyenner des puissances.",
    ex: "144 points de 10 min deviennent 1 énergie journalière.",
    etapes: [4],
  },
  "sous-compteur": {
    terme: "Sous-compteur",
    def: "Un compteur privé placé en aval du compteur principal pour mesurer une partie des usages (une cuisine, un étage). Il ne s’additionne pas au compteur principal.",
    ex: "Un sous-compteur sur la cuisine de l’école mesurerait environ 2 MWh par an, déjà inclus dans les 86 MWh du compteur principal.",
    etapes: [1, 4],
  },
  "data-connect": {
    terme: "Enedis Data Connect",
    def: "L’API d’Enedis qui permet à un tiers autorisé de récupérer les données d’un compteur Linky (≤ 36 kVA), avec le consentement du client. Une nouvelle version a été mise en service le 28 septembre 2026 (à vérifier).",
    ex: "Elle ne s’applique pas à l’école, raccordée en C4 au-delà de 36 kVA.",
    etapes: [2],
    src: ["enedis-contrat-data-connect", "github-bascule-data-connect"],
  },
  sge: {
    terme: "SGE (Enedis)",
    def: "Le système de gestion des échanges d’Enedis : portail et web services qui donnent accès aux données des compteurs, notamment au-delà de 36 kVA, pour des tiers habilités avec le consentement du client.",
    ex: "C’est par ce canal qu’un EMS récupérerait la courbe au pas de 10 min de l’école.",
    etapes: [2],
    src: ["enedis-contrat-sge", "enedis-sge-fournisseur"],
  },
  adict: {
    terme: "GRDF ADICT",
    def: "L’API de GRDF qui donne accès, avec le consentement du client, aux consommations de gaz (quotidiennes, mensuelles, semestrielles) et aux données du compteur et du contrat.",
    ex: "L’EMS y récupère chaque jour les dernières consommations Gazpar publiées, avec 1 à 3 jours de décalage.",
    etapes: [2],
    src: ["grdf-adict-faq", "grdf-guide-donnees-2026"],
  },
  thermosensibilite: {
    terme: "Thermosensibilité",
    def: "Le nombre de kWh de chauffage en plus pour chaque degré-jour de froid : la pente de la signature énergétique.",
    ex: "Environ 134 kWh de gaz par DJU un jour de classe.",
    etapes: [5],
  },
  "normalisation-climatique": {
    terme: "Correction climatique",
    def: "Ramener une consommation de chauffage aux DJU d’une année de référence, pour comparer des hivers différents.",
    ex: "150 000 kWh pour 1 900 DJU valent 177 158 kWh à 2 244 DJU.",
    etapes: [5, 8],
  },
  ratio: {
    terme: "Ratio de consommation",
    def: "Une consommation divisée par une grandeur de taille ou d’activité (m², élève, repas) pour comparer des bâtiments.",
    ex: "147 kWh/m² tous usages pour l’école.",
    etapes: [5],
  },
  "seuil-alerte": {
    terme: "Seuil d’alerte",
    def: "L’écart à la référence au-delà duquel le logiciel signale une anomalie, parfois avec une durée minimale (persistance).",
    ex: "Plus de 10 % au-dessus de la référence, deux jours de suite.",
    etapes: [3, 6],
  },
  "faux-positif": {
    terme: "Faux positif / faux négatif",
    def: "Une alerte sans vrai problème (faux positif), ou un vrai problème sans alerte (faux négatif).",
    ex: "Le pic à 999,9 kW déclenche une fausse alerte ; un seuil à 40 % laisse passer la dérive de janvier.",
    etapes: [6],
  },
  sobriete: {
    terme: "Sobriété / efficacité",
    def: "Sobriété : consommer moins en changeant les usages. Efficacité : obtenir le même service avec moins d’énergie grâce à de meilleurs équipements.",
    ex: "Baisser la consigne (sobriété) ; passer aux LED (efficacité).",
    etapes: [7],
  },
  autoconsommation: {
    terme: "Autoconsommation",
    def: "Consommer sur place l’électricité qu’on produit. Le taux d’autoconsommation est la part de la production consommée sur place ; le surplus part sur le réseau.",
    ex: "Avec 36 kWc, l’école consomme sur place une partie seulement de sa production d’été.",
    etapes: [7],
  },
  kwc: {
    terme: "kWc",
    def: "Kilowatt-crête : la puissance maximale d’une installation solaire dans des conditions standard d’ensoleillement.",
    ex: "36 kWc produisent environ 38 MWh par an en Île-de-France (ordre de grandeur).",
    etapes: [7],
  },
  "temps-de-retour": {
    terme: "Temps de retour",
    def: "Le nombre d’années pour que les économies remboursent l’investissement : investissement divisé par l’économie annuelle.",
    ex: "30 000 € d’isolation pour 2 500 € d’économie par an : 12 ans.",
    etapes: [7],
  },
  "energie-finale": {
    terme: "Énergie finale",
    def: "L’énergie livrée et facturée au bâtiment (kWh d’électricité, de gaz), par opposition à l’énergie primaire nécessaire pour la produire.",
    ex: "Le décret tertiaire compte l’énergie finale de l’école : environ 294 MWh.",
    etapes: [8],
  },
  ipmvp: {
    terme: "IPMVP",
    def: "Le protocole international de mesure et de vérification de la performance, qui encadre la façon de prouver une économie d’énergie.",
    ex: "Il impose de fixer à l’avance la période de référence et l’ajustement aux DJU.",
    etapes: [8],
  },
  ipe: {
    terme: "IPÉ",
    def: "Indicateur de performance énergétique (ISO 50001) : une mesure choisie pour suivre la performance, comme les kWh/m² ou les kWh/DJU.",
    ex: "L’école suit ses kWh de gaz par DJU chaque mois.",
    etapes: [8],
  },
  perimetre: {
    terme: "Périmètre",
    def: "Ce qu’on décide de suivre : un patrimoine, un site, un bâtiment, un usage. Tout ce qui est dedans est mesuré et comparé ; le reste est laissé de côté, volontairement.",
    ex: "Le périmètre de l’école : le bâtiment et la cour, sans le logement du gardien, qui a son propre compteur.",
    etapes: [1],
  },
  anomalie: {
    terme: "Anomalie (de donnée)",
    def: "Une valeur qui ne peut pas être juste : un trou, un doublon, un pic impossible, une valeur négative, une mauvaise unité. On la repère, on la marque, on ne l’efface jamais.",
    ex: "Un pic à 999,9 kW sur un raccordement de 60 kVA est une anomalie.",
    etapes: [3],
  },
  pointe: {
    terme: "Pointe",
    def: "La puissance la plus haute appelée sur une période. C’est elle qui doit tenir sous la puissance souscrite.",
    ex: "La pointe annuelle de l’école est de 57 kVA, un midi d’hiver.",
    etapes: [5, 7],
  },
  derive: {
    terme: "Dérive",
    def: "Une hausse de consommation qui s’installe et dure, par rapport à la référence : un équipement oublié, un réglage modifié, une panne.",
    ex: "Un équipement resté allumé la nuit fait monter le talon de l’école de 3 kW.",
    etapes: [6],
  },
  indicateur: {
    terme: "Indicateur",
    def: "Un chiffre suivi dans le temps pour savoir si l’on progresse : kWh, kWh/m², euros, CO2. On le choisit selon l’objectif.",
    ex: "L’école suit ses kWh/m² par an, ses euros et ses tonnes de CO2.",
    etapes: [1, 8],
  },
  pci: {
    terme: "PCI",
    def: "Pouvoir calorifique inférieur : l’énergie d’un combustible sans la chaleur qu’on récupérerait en condensant la vapeur d’eau des fumées. Le gaz se facture en PCS, environ 11 % au-dessus du PCI : un même facteur d’émission change donc selon la base.",
    ex: "≈ 0,204 kg de CO2 par kWh de gaz facturé (PCS), soit ≈ 0,227 kg par kWh PCI.",
    etapes: [8],
  },
  talon: {
    terme: "Talon",
    def: "La puissance minimale appelée quand le bâtiment est vide (nuit, week-end) : les appareils qui ne s’arrêtent jamais.",
    ex: "Le talon de l’école est d’environ 6 kW : serveurs, frigos, ventilation réduite.",
    etapes: [5, 6],
  },
  baseline: {
    terme: "Baseline (référence)",
    def: "La consommation « normale » attendue, qui sert de point de comparaison pour repérer une dérive ou mesurer une économie.",
    ex: "La référence de l’école est son année 2025-2026 sans dérive.",
    etapes: [6, 8],
  },
  dju: {
    terme: "DJU",
    def: "Degrés-Jours Unifiés : pour chaque jour, l’écart entre 18 °C et la température moyenne extérieure quand elle est plus basse, additionné sur la période. Plus il y a de DJU, plus l’hiver est froid.",
    ex: "Un jour à 6 °C de moyenne compte 12 DJU. L’école cumule environ 2 240 DJU sur l’année.",
    etapes: [5, 8],
  },
  signature: {
    terme: "Signature énergétique",
    def: "La relation entre la consommation de chauffage et les DJU, souvent une droite : chaque DJU coûte à peu près le même nombre de kWh.",
    ex: "Pour l’école, environ 134 kWh de gaz par DJU un jour de classe.",
    etapes: [5, 8],
  },
  "puissance-souscrite": {
    terme: "Puissance souscrite",
    def: "La puissance maximale prévue au contrat. La part fixe de l’acheminement en dépend et, selon l’offre, l’abonnement du fournisseur.",
    ex: "L’école a souscrit 60 kVA.",
    etapes: [5, 7],
  },
  depassement: {
    terme: "Dépassement de puissance",
    def: "Quand la puissance appelée dépasse la puissance souscrite. En C4, il est facturé en pénalités ; jusqu’à 36 kVA, le compteur coupe.",
    ex: "Avec des radiateurs d’appoint en janvier, l’école monte à 70 kVA.",
    etapes: [5, 6],
  },
  mv: {
    terme: "M&V",
    def: "Mesure et Vérification : la méthode pour prouver une économie en comparant la consommation réelle à une référence ajustée (météo, occupation).",
    ex: "On corrige l’hiver doux avant de dire que la nouvelle régulation a fait gagner 10 %.",
    etapes: [8],
  },
  operat: {
    terme: "OPERAT",
    def: "La plateforme de l’ADEME où les assujettis au décret tertiaire déclarent chaque année leurs consommations.",
    ex: "La mairie déclare l’école (2 000 m²) sur OPERAT.",
    etapes: [8],
  },
  "decret-tertiaire": {
    terme: "Décret tertiaire",
    def: "L’obligation, pour les bâtiments tertiaires d’au moins 1 000 m², de réduire leur consommation d’énergie finale : −40 % en 2030, −50 % en 2040 et −60 % en 2050 par rapport à une année de référence, ou d’atteindre un seuil en valeur absolue (à vérifier).",
    ex: "Avec 2 000 m², l’école est concernée.",
    etapes: [1, 8],
  },
  iso50001: {
    terme: "ISO 50001",
    def: "La norme internationale des systèmes de management de l’énergie, fondée sur la boucle planifier, faire, vérifier, agir.",
    ex: "Le cycle en 8 étapes de ce site suit cette même logique.",
    etapes: [1, 8],
  },
  tco2: {
    terme: "tCO2e",
    def: "Tonne équivalent CO2 : l’unité commune pour additionner l’effet de différents gaz à effet de serre.",
    ex: "Le gaz de l’école émet bien plus de CO2 par kWh que son électricité (facteurs à vérifier).",
    etapes: [8],
  },
};

/** Les clés des termes, par ordre alphabétique. */
export const termesTries = () =>
  Object.keys(GLOSSAIRE).sort((e, n) => GLOSSAIRE[e].terme.localeCompare(GLOSSAIRE[n].terme, "fr"));
