/**
 * Le registre des sources : chaque référence citée par le cours et par le jeu, une seule fois.
 *
 * Une source : sa clé, puis { t : titre, ed : éditeur, date : date du document (si elle est connue), url : le lien,
 *   niveau : "officiel" (texte, régulateur, gestionnaire de réseau, organisme public ou de recherche) ou "secondaire" (presse, fabricant, projet open source),
 *   vu : le jour où la page a été ouverte et lue }.
 *
 * Pour citer une source :
 *   - dans un texte du cours : [[cle]] ou [[cle-1,cle-2]] juste après l'information (cela affiche un appel de note numéroté) ;
 *   - dans une fiche savoir du jeu ou une information de voyage : refs:['cle-1','cle-2'].
 * Le passage exact lu dans chaque source, information par information, est gardé dans outils/sources/ (les relevés).
 * `node outils/sources.mjs` contrôle que chaque clé citée existe ici et fabrique le tableau de relecture.
 */
export const SOURCES = {
  "ademe-empreinte-pv-2026": {
    t: "Photovoltaïque : les données de référence actualisées confirment la baisse de l’empreinte carbone de l’électricité solaire (communiqué)",
    ed: "ADEME",
    date: "1er septembre 2026",
    url: "https://www.ademe.fr/presse/communique-national/photovoltaique-une-collaboration-francaise-inedite-actualise-les-donnees-de-reference-et-confirme-la-baisse-de-lempreinte-carbone-de-lelectricite-solaire/",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "ademe-operat-faq": {
    t: "FAQ Éco Énergie Tertiaire (plateforme OPERAT)",
    ed: "ADEME",
    date: "mise à jour d’août 2026",
    url: "https://operat.ademe.fr/public/faq",
    niveau: "officiel",
    vu: "2026-10-09",
  },
  "panorama-enr-2025": {
    t: "Panorama de l’électricité renouvelable au 31 décembre 2025",
    ed: "Agence ORE, Enedis, RTE, SER",
    date: "31 décembre 2025",
    url: "https://www.syndicat-energies-renouvelables.fr/wp-content/uploads/2026/07/SER_panoramaEnR-2025-3.pdf",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "cea-cellules-pv": {
    t: "L’essentiel sur les cellules photovoltaïques",
    ed: "CEA",
    date: "1er mars 2022",
    url: "https://www.cea.fr/comprendre/Pages/energies/renouvelables/essentiel-sur-cellules-photovoltaiques.aspx",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "cnieg-cta-2026": {
    t: "Révision des taux de la contribution tarifaire d’acheminement (CTA) électricité depuis le 1er février 2026",
    ed: "CNIEG",
    date: "24 février 2026",
    url: "https://www.cnieg.fr/accueil/actualites/revision-cta.html",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "cnieg-cta-note": {
    t: "Note d’information sur la déclaration de contribution tarifaire d’acheminement (CTA)",
    ed: "CNIEG",
    date: null,
    url: "https://www.cnieg.fr/files/live/sites/portail/files/documents/Entreprise/E-cta-note-information-actualisee.pdf",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "cnil-deliberation-2012-404": {
    t: "Délibération n° 2012-404 du 15 novembre 2012 : recommandation sur les données de consommation détaillées des compteurs communicants",
    ed: "CNIL",
    date: "15 novembre 2012",
    url: "https://www.cnil.fr/sites/cnil/files/2023-10/recommandation_compteurs_communicants.pdf",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "cnil-donnee-personnelle": {
    t: "Définition : donnée personnelle",
    ed: "CNIL",
    date: null,
    url: "https://www.cnil.fr/fr/definition/donnee-personnelle",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "cnil-linky-courbe-de-charge": {
    t: "Compteurs communicants Linky : la position de la CNIL sur le stockage local de la courbe de charge",
    ed: "CNIL",
    date: "30 novembre 2015",
    url: "https://www.cnil.fr/fr/compteurs-communicants-linky-la-position-de-la-cnil-sur-le-stockage-local-de-la-courbe-de-charge-0",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "cnil-linky-gazpar": {
    t: "Linky, Gazpar : quelles données sont collectées et transmises par les compteurs communicants ?",
    ed: "CNIL",
    date: "31 octobre 2017",
    url: "https://www.cnil.fr/fr/linky-gazpar-quelles-donnees-sont-collectees-et-transmises-par-les-compteurs-communicants",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "cnil-minimisation": {
    t: "Définition : minimisation",
    ed: "CNIL",
    date: null,
    url: "https://www.cnil.fr/fr/definition/minimisation",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "cnil-rgpd": {
    t: "RGPD : de quoi parle-t-on ?",
    ed: "CNIL",
    date: "10 avril 2018",
    url: "https://www.cnil.fr/fr/rgpd-de-quoi-parle-t-on",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "consometers-data-connect": {
    t: "Notre expérience avec le service Data Connect d’Enedis (dépôt GitHub)",
    ed: "Consometers (association)",
    date: null,
    url: "https://github.com/consometers/data-connect",
    niveau: "secondaire",
    vu: "2026-10-06",
  },
  "consometers-sge-tiers": {
    t: "Retour d’expérience sur SGE Tiers d’Enedis (dépôt GitHub)",
    ed: "Consometers (association)",
    date: null,
    url: "https://github.com/consometers/sge-tiers",
    niveau: "secondaire",
    vu: "2026-10-06",
  },
  "cre-atrd7": {
    t: "La CRE fixe le tarif des réseaux de distribution de gaz naturel de GRDF pour la période 2024-2027",
    ed: "CRE",
    date: "2 février 2024",
    url: "https://www.cre.fr/actualites/toute-lactualite/la-cre-fixe-le-tarif-des-reseaux-de-distribution-de-gaz-naturel-de-grdf-pour-la-periode-2024-2027.html",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "cre-avis-cta-2026": {
    t: "Avis sur le projet d’arrêté relatif aux taux de la contribution tarifaire d’acheminement (CTA)",
    ed: "CRE",
    date: "29 janvier 2026",
    url: "https://www.cre.fr/actualites/toute-lactualite/la-cre-publie-son-avis-sur-le-projet-darrete-relatif-aux-taux-de-la-contribution-tarifaire-sur-les-prestations-cta-de-transport-et-de-distribution-delectricite-et-de-gaz-naturel.html",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "cre-compteurs-evolues": {
    t: "Maitrise de sa consommation en période de crise grâce aux compteurs évolués",
    ed: "CRE",
    date: "3 novembre 2022",
    url: "https://www.cre.fr/actualites/notre-magazine-parlons-energie/parlons-energie-n8/maitrise-de-sa-consommation-en-periode-de-crise-grace-aux-compteurs-evolues.html",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "cre-deliberation-2026-105": {
    t: "Délibération n° 2026-105 du 21 mai 2026 : évolution du TURPE 7 HTA-BT au 1er août 2026",
    ed: "CRE",
    date: "21 mai 2026",
    url: "https://www.cre.fr/fileadmin/Documents/Deliberations/2026/260521_2026-105_Evolution_TURPE_7_HTA-BT.pdf",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "cre-heures-creuses": {
    t: "TURPE 7 : évolution du placement des heures creuses (annexe au communiqué de presse)",
    ed: "CRE",
    date: "6 février 2025",
    url: "https://www.cre.fr/fileadmin/Documents/Communiques_de_presse/2025/250206_Annexe_CP_TURPE_7_HPHC.pdf",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "cre-prix-negatifs": {
    t: "Analyse du phénomène de prix négatifs de l’électricité et recommandations",
    ed: "CRE",
    date: "26 novembre 2024",
    url: "https://www.cre.fr/fileadmin/Documents/Rapports_et_etudes/2024/241126_Note_Prix_negatifs.pdf",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "cre-services-systeme": {
    t: "Services système et mécanisme d’ajustement",
    ed: "CRE",
    date: "29 avril 2024",
    url: "https://www.cre.fr/electricite/reseaux-delectricite/services-systeme-et-mecanisme-dajustement.html",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "cre-tarif-acces": {
    t: "Réseaux d’électricité : le tarif d’accès",
    ed: "CRE",
    date: null,
    url: "https://www.cre.fr/electricite/reseaux-delectricite/tarif-dacces.html",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "cre-tarifs-gaz": {
    t: "Tarifs d’utilisation des infrastructures de transport, de stockage et de distribution de gaz naturel (lettre d’information)",
    ed: "CRE",
    date: "janvier 2020",
    url: "https://www.cre.fr/actualites/nos-lettres-dinformation/tarifs-d-utilisation-des-infrastructures-de-transport-de-stockage-et-de-distribution-de-gaz-naturel-atrt7-ats2-et-atrd6.html",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "datagouv-grdf-adict": {
    t: "API GRDF ADICT (fiche du service)",
    ed: "data.gouv.fr (fiche GRDF)",
    date: null,
    url: "https://www.data.gouv.fr/dataservices/api-grdf-adict",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "edf-chooz": {
    t: "Centrale nucléaire de Chooz",
    ed: "EDF",
    date: "23 juin 2026",
    url: "https://www.edf.fr/centrale-nucleaire-chooz",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "edf-consommation-chiffres": {
    t: "La consommation d’électricité en chiffres",
    ed: "EDF",
    date: "27 août 2026",
    url: "https://www.edf.fr/groupe-edf/comprendre/electricite-au-quotidien/usages/consommation-electricite-en-chiffres",
    niveau: "secondaire",
    vu: "2026-10-06",
  },
  "edf-gravelines": {
    t: "La centrale nucléaire de Gravelines",
    ed: "EDF",
    date: "23 septembre 2026",
    url: "https://www.edf.fr/centrale-nucleaire-gravelines",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "edf-solaire-chiffres": {
    t: "Le solaire photovoltaïque en chiffres",
    ed: "EDF",
    date: "27 août 2026",
    url: "https://www.edf.fr/groupe-edf/comprendre/production/solaire/solaire-photovoltaique-en-chiffres",
    niveau: "secondaire",
    vu: "2026-10-06",
  },
  "enedis-acces-donnees": {
    t: "Accéder aux données fournies par Enedis",
    ed: "Enedis",
    date: "6 octobre 2025",
    url: "https://www.enedis.fr/acceder-aux-donnees-fournies-par-enedis",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "enedis-contrat-data-connect": {
    t: "Modèle de contrat d’utilisation du service Data Connect (Enedis-MOP-NUM_010E)",
    ed: "Enedis",
    date: "15 septembre 2025",
    url: "https://www.enedis.fr/media/1924/download",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "enedis-contrat-sge": {
    t: "Modèle de contrat d’accès à la plateforme d’échanges SGE pour les tiers autorisés (Enedis-MOP-CF_054E, version 1.2)",
    ed: "Enedis",
    date: "1er juin 2026",
    url: "https://www.enedis.fr/media/1921/download",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "enedis-donnees-personnelles": {
    t: "Données personnelles",
    ed: "Enedis",
    date: null,
    url: "https://www.enedis.fr/donnees-personnelles",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "enedis-facturation-acheminement": {
    t: "Comprendre la facturation de l’acheminement",
    ed: "Enedis",
    date: null,
    url: "https://www.enedis.fr/marche-electricite-facturation",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "enedis-guide-flux-r6x": {
    t: "Guide d’implémentation des flux R6X : R63 (courbe de charge) et R64 (index), version 2.0",
    ed: "Enedis",
    date: "29 novembre 2023",
    url: "https://www.enedis.fr/media/3751/download",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "enedis-linky": {
    t: "Tout savoir sur Linky, le compteur adapté à la vie d’aujourd’hui",
    ed: "Enedis",
    date: "30 juillet 2026",
    url: "https://www.enedis.fr/tout-savoir-sur-linky-le-compteur-adapte-la-vie-daujourdhui",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "enedis-linky-facilite": {
    t: "Le compteur Linky vous facilite la vie",
    ed: "Enedis",
    date: null,
    url: "https://www.enedis.fr/le-compteur-linky-vous-facilite-la-vie",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "enedis-mes-donnees": {
    t: "J’accède à mes données de mesure",
    ed: "Enedis",
    date: "30 juin 2021",
    url: "https://www.enedis.fr/jaccede-mes-donnees-de-mesure",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "enedis-modele-autorisation": {
    t: "Modèle d’autorisation de communication à un tiers des données de mesure (Enedis-MOP-CF_041E)",
    ed: "Enedis",
    date: "15 septembre 2025",
    url: "https://www.enedis.fr/media/3224/download",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "enedis-nmo-cf-015e": {
    t: "Modalités d’accès aux données des sites raccordés en HTA ou en BT > 36 kVA (Enedis-NMO-CF_015E, version 2)",
    ed: "Enedis",
    date: "3 juillet 2026",
    url: "https://www.enedis.fr/media/2128/download",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "enedis-nmo-cf-016e": {
    t: "Modalités d’accès aux données des sites BT ≤ 36 kVA équipés d’un compteur communicant (Enedis-NMO-CF_016E, version 2)",
    ed: "Enedis",
    date: "3 juillet 2026",
    url: "https://www.enedis.fr/media/2127/download",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "enedis-nmo-cf-077e": {
    t: "Publication récurrente des données de mesure des compteurs BT > 36 kVA et HTA : identification et traitement des dysfonctionnements (Enedis-NMO-CF_077E, version 2)",
    ed: "Enedis",
    date: "3 juillet 2026",
    url: "https://www.enedis.fr/media/4688/download",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "enedis-pdl": {
    t: "Où trouver le numéro point de livraison (PDL) du compteur Linky ?",
    ed: "Enedis",
    date: "26 août 2026",
    url: "https://www.enedis.fr/faq/compteur-linky/ou-trouver-le-numero-point-de-livraison-pdl-du-compteur-linky",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "enedis-protections-decouplage": {
    t: "Protections de découplage des installations de production raccordées au réseau public de distribution (Enedis-PRO-RES_10E, version 7)",
    ed: "Enedis",
    date: "1er janvier 2025",
    url: "https://www.enedis.fr/media/2162/download",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "enedis-segments-c1-c5": {
    t: "À quoi correspondent les points de connexion C1 à C5 ?",
    ed: "Enedis",
    date: null,
    url: "https://www.enedis.fr/faq/glossaire/quoi-correspondent-les-points-de-connexion-c1-c5",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "enedis-sge-fournisseur": {
    t: "Je souhaite devenir un fournisseur d’électricité",
    ed: "Enedis",
    date: null,
    url: "https://www.enedis.fr/devenir-fournisseur-energie-sge",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "enedis-technologies-enr": {
    t: "Technologies pour la production d’électricité renouvelable (supplément technique)",
    ed: "Enedis",
    date: "mai 2019",
    url: "https://www.enedis.fr/sites/default/files/documents/pdf/supplement-technique-technologies-production-electricite-renouvelable.pdf?VersionId=BiB_SAGWoSsKStdWMIYv_WS2y8nmMes5",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "enedis-turpe6-essentiel": {
    t: "TURPE 6 HTA/BT : l’essentiel (tarifs au 1er février 2025)",
    ed: "Enedis",
    date: "1er février 2025",
    url: "https://www.enedis.fr/sites/default/files/documents/pdf/enedis-essentiel-turpe6.pdf",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "enedis-turpe7-brochure": {
    t: "TURPE 7 HTA/BT : tarifs en vigueur au 1er août 2026 (brochure tarifaire)",
    ed: "Enedis",
    date: "1er août 2026",
    url: "https://www.enedis.fr/sites/default/files/documents/pdf/brochure-tarifaire-turpe-7.pdf",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "fraunhofer-pv-report": {
    t: "Photovoltaics Report",
    ed: "Fraunhofer ISE",
    date: "14 juillet 2026",
    url: "https://www.ise.fraunhofer.de/content/dam/ise/de/documents/publications/studies/Photovoltaics-Report.pdf",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "github-eddie-data-connect": {
    t: "Enedis Region Connector: Update to new API (ticket n° 2549, projet EDDIE)",
    ed: "GitHub (projet EDDIE)",
    date: null,
    url: "https://github.com/eddie-energy/eddie/issues/2549",
    niveau: "secondaire",
    vu: "2026-10-06",
  },
  "github-bascule-data-connect": {
    t: "Support de la bascule Enedis Data Connect du 28/09/2026 (demande de fusion n° 1, projet homey.enedis.connect.proxy)",
    ed: "GitHub (projet open source)",
    date: null,
    url: "https://github.com/c-fevre/homey.enedis.connect.proxy/pull/1",
    niveau: "secondaire",
    vu: "2026-10-06",
  },
  "gsa-lille": {
    t: "Global Solar Atlas : productible à long terme, Lille (50,63° N ; 3,06° E)",
    ed: "Global Solar Atlas (Banque mondiale)",
    date: null,
    url: "https://api.globalsolaratlas.info/data/lta?loc=50.63,3.06",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "gsa-nevers": {
    t: "Global Solar Atlas : productible à long terme, Nevers (46,99° N ; 3,16° E)",
    ed: "Global Solar Atlas (Banque mondiale)",
    date: null,
    url: "https://api.globalsolaratlas.info/data/lta?loc=46.99,3.16",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "gsa-orleans": {
    t: "Global Solar Atlas : productible à long terme, Orléans (47,90° N ; 1,90° E)",
    ed: "Global Solar Atlas (Banque mondiale)",
    date: null,
    url: "https://api.globalsolaratlas.info/data/lta?loc=47.90,1.90",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "gsa-saint-photon": {
    t: "Global Solar Atlas : productible à long terme, arrière-pays provençal (44,0° N ; 5,95° E)",
    ed: "Global Solar Atlas (Banque mondiale)",
    date: null,
    url: "https://api.globalsolaratlas.info/data/lta?loc=44.0,5.95",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "grdf-adict-consentement": {
    t: "Formulaire de consentement type GRDF ADICT",
    ed: "GRDF",
    date: null,
    url: "https://sites.grdf.fr/documents/44859/0/Mod%C3%A8le+de+consentement.pdf/e90ad8d0-3450-21c5-2850-66b4e522c8c1?version=1.1&t=1613987772178&download=true",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "grdf-adict-contrat": {
    t: "Contrat d’accès au service GRDF ADICT (version de mai 2024)",
    ed: "GRDF",
    date: "mai 2024",
    url: "https://sites.grdf.fr/documents/44859/0/GRDF+ADICT+MULTICANAL+-+Contrat+-+Vdef.pdf/e6c5cf19-c503-efc6-d16d-d1d0f95ee8cc?t=1696611202635",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "grdf-adict-faq": {
    t: "Portail API GRDF ADICT : foire aux questions",
    ed: "GRDF",
    date: null,
    url: "https://sites.grdf.fr/web/portail-api-grdf-adict/faq",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "grdf-coefficient-conversion": {
    t: "Coefficient de conversion gaz : comment le calculer ?",
    ed: "GRDF",
    date: null,
    url: "https://www.grdf.fr/particuliers/logement-gaz/premiers-pas/coefficient-conversion-commune",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "grdf-coefficients-thermiques": {
    t: "Comprendre les coefficients thermiques (ou coefficients de conversion en énergie)",
    ed: "GRDF",
    date: null,
    url: "https://www.grdf.fr/documents/10184/1291504/Q-R+coefficients+thermiques+vF.pdf/b5ab70f1-66c0-400e-b362-bc4ff5de3c05",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "grdf-compteur-communicant": {
    t: "Tout savoir sur le compteur communicant gaz",
    ed: "GRDF",
    date: null,
    url: "https://www.grdf.fr/particuliers/informations-compteur-gaz-communicant-grdf",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "grdf-guide-donnees-2026": {
    t: "Guide utilisateur : la gestion avancée des données de consommation (version 1.6)",
    ed: "GRDF",
    date: "28 janvier 2026",
    url: "https://sites.grdf.fr/documents/44859/0/GRDF_EC_Guide_Utilisateur_28012026.pdf/6d2ca79f-bd81-acd1-5b2b-a2a79f70ef97?version=1.0&t=1769606570704&download=true",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "grdf-prescriptions-techniques": {
    t: "Prescriptions techniques du distributeur GRDF",
    ed: "GRDF",
    date: "avril 2017",
    url: "https://projet-methanisation.grdf.fr/cms-assets/2019/07/Prescriptions_techniques_GRDF.pdf",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "iea-pvps-acv": {
    t: "Task 12, Methodology Guidelines on Life Cycle Assessment of Photovoltaic Electricity (4e édition)",
    ed: "IEA-PVPS",
    date: "avril 2020",
    url: "https://iea-pvps.org/wp-content/uploads/2020/07/IEA_Task12_LCA_Guidelines.pdf",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "iea-pvps-prevision": {
    t: "Task 16, Regional solar power forecasting (rapport T16-01:2020, résumé)",
    ed: "IEA-PVPS",
    date: "mai 2020",
    url: "https://iea-pvps.org/wp-content/uploads/2020/07/IEA_PVPS_T16_regional_forecasts_summary.pdf",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "iea-pvps-salissures": {
    t: "Task 13, Soiling Losses: Impact on the Performance of Photovoltaic Power Plants",
    ed: "IEA-PVPS",
    date: "janvier 2023",
    url: "https://iea-pvps.org/key-topics/soiling-losses-impact-on-the-performance-of-photovoltaic-power-plants/",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "iea-pvps-trackers": {
    t: "Task 13, fiche « Bifacial Tracking »",
    ed: "IEA-PVPS",
    date: "juillet 2024",
    url: "https://iea-pvps.org/wp-content/uploads/2024/07/Task-13-Bifacial-Tracking-Fact-Sheet.pdf",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "inrae-paturage-pv": {
    t: "Une étude confirme les effets positifs des panneaux photovoltaïques sur le pâturage ovin",
    ed: "INRAE",
    date: "25 avril 2024",
    url: "https://www.inrae.fr/actualites/etude-confirme-effets-positifs-panneaux-photovoltaiques-paturage-ovin",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "insee-bilan-demographique-2025": {
    t: "Bilan démographique 2025 (Insee Première n° 2087)",
    ed: "Insee",
    date: "13 janvier 2026",
    url: "https://www.insee.fr/fr/statistiques/8719824?sommaire=8721209",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "krannich-onduleur-350": {
    t: "Fiche de l’onduleur Sungrow SG350HX (350 kW)",
    ed: "Krannich Solar (distributeur)",
    date: null,
    url: "https://shop.krannich-solar.com/de-en/inverters/solar-inverters/54501/sg350hx-v114-350-kw",
    niveau: "secondaire",
    vu: "2026-10-06",
  },
  "lbnl-surface-pv": {
    t: "Land Requirements for Utility-Scale PV: An Empirical Update on Power and Energy Density (Bolinger & Bolinger)",
    ed: "Lawrence Berkeley National Laboratory",
    date: "2022",
    url: "https://emp.lbl.gov/sites/default/files/emp-files/land_requirements_for_utility-scale_pv.pdf",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "legifrance-r341-5": {
    t: "Code de l’énergie, article R. 341-5",
    ed: "Légifrance",
    date: "1er janvier 2016",
    url: "https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000031749067",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "legifrance-cch-r174-22": {
    t: "Code de la construction et de l’habitation, article R. 174-22 (champ d’application de l’obligation de réduction des consommations dans les bâtiments tertiaires)",
    ed: "Légifrance",
    date: "1er juillet 2021",
    url: "https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000043819501",
    niveau: "officiel",
    vu: "2026-10-09",
  },
  "legifrance-arrete-tertiaire-2020": {
    t: "Arrêté du 10 avril 2020 relatif aux obligations d’actions de réduction des consommations d’énergie finale dans des bâtiments à usage tertiaire (« arrêté méthode »), version en vigueur au 9 octobre 2026",
    ed: "Légifrance",
    date: "3 mai 2020, dernière mise à jour le 20 août 2026",
    url: "https://www.legifrance.gouv.fr/loda/id/JORFTEXT000041842389",
    niveau: "officiel",
    vu: "2026-10-09",
  },
  "ministere-autoconsommation": {
    t: "Systèmes d’autoconsommation",
    ed: "Ministère chargé de l’énergie",
    date: "19 décembre 2023",
    url: "https://www.ecologie.gouv.fr/politiques-publiques/systemes-dautoconsommation",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "ministere-guide-fiscalite-2026": {
    t: "Guide 2026 sur la fiscalité des énergies",
    ed: "Ministère chargé de l’énergie",
    date: "2026",
    url: "https://www.ecologie.gouv.fr/sites/default/files/documents/Guide%202026%20sur%20fiscalit%C3%A9%20des%20%C3%A9nergies.pdf",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "minefi-tva": {
    t: "La TVA, qu’est-ce que c’est ?",
    ed: "Ministère de l’Économie",
    date: null,
    url: "https://www.economie.gouv.fr/facileco/la-tva-quest-ce-que-cest",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "mne-acteurs-marche": {
    t: "Les acteurs du marché",
    ed: "Médiateur national de l’énergie",
    date: "22 mai 2025",
    url: "https://www.energie-info.fr/fiche_pratique/les-acteurs-du-marche/",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "mne-changer-fournisseur": {
    t: "Je souhaite changer de fournisseur d’électricité ou de gaz naturel ?",
    ed: "Médiateur national de l’énergie",
    date: "4 novembre 2025",
    url: "https://www.energie-info.fr/fiche_pratique/je-souhaite-changer-de-fournisseur-delectricite-ou-de-gaz-naturel/",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "mne-coefficient-conversion": {
    t: "Glossaire : coefficient de conversion du gaz naturel",
    ed: "Médiateur national de l’énergie",
    date: null,
    url: "https://www.energie-info.fr/glossary/coefficient-de-conversion-du-gaz-naturel/",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "mne-compteurs-communicants": {
    t: "Les compteurs communicants Linky et Gazpar",
    ed: "Médiateur national de l’énergie",
    date: "27 mai 2025",
    url: "https://www.energie-info.fr/pro/fiche_pratique/les-compteurs-communicants-linky-et-gazpar/",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "mne-contrat-unique": {
    t: "Glossaire : contrat unique",
    ed: "Médiateur national de l’énergie",
    date: null,
    url: "https://www.energie-info.fr/glossary/contrat-unique/",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "mne-elements-facture": {
    t: "Les différents éléments de ma facture",
    ed: "Médiateur national de l’énergie",
    date: "30 juillet 2025",
    url: "https://www.energie-info.fr/fiche_pratique/les-differents-elements-de-ma-facture/",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "mne-frequence-facturation": {
    t: "La fréquence de facturation et les modes de paiement",
    ed: "Médiateur national de l’énergie",
    date: "20 février 2026",
    url: "https://www.energie-info.fr/fiche_pratique/la-frequence-de-facturation-et-les-modes-de-paiement/",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "mne-lire-index": {
    t: "Comment lire les index sur mon compteur d’électricité ou de gaz naturel ?",
    ed: "Médiateur national de l’énergie",
    date: "20 février 2026",
    url: "https://www.energie-info.fr/fiche_pratique/comment-lire-les-index-sur-mon-compteur-delectricite-ou-de-gaz/",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "mne-pcs": {
    t: "Glossaire : pouvoir calorifique supérieur du gaz naturel",
    ed: "Médiateur national de l’énergie",
    date: null,
    url: "https://www.energie-info.fr/pro/glossary/pouvoir-calorifique-superieur-du-gaz-naturel/",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "mne-prix": {
    t: "Prix de l’électricité et du gaz : que payons-nous ?",
    ed: "Médiateur national de l’énergie",
    date: "1er octobre 2026",
    url: "https://www.energie-info.fr/fiche_pratique/prix-de-lelectricite-et-du-gaz-que-payons-nous/",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "mne-prix-pro": {
    t: "Prix de l’électricité et du gaz : que payons-nous ?",
    ed: "Médiateur national de l’énergie",
    date: "27 mai 2025",
    url: "https://www.energie-info.fr/pro/fiche_pratique/prix-de-lelectricite-et-du-gaz-que-payons-nous/",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "mne-releve-compteur": {
    t: "Relevé des compteurs et calcul de la consommation",
    ed: "Médiateur national de l’énergie",
    date: "4 novembre 2025",
    url: "https://www.energie-info.fr/fiche_pratique/releve-compteur-calcul-consommation/",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "mne-taxes-facture": {
    t: "Accise, CTA et TVA : les trois taxes et contributions sur mes factures d’électricité et de gaz naturel",
    ed: "Médiateur national de l’énergie",
    date: "3 septembre 2026",
    url: "https://www.energie-info.fr/fiche_pratique/cspe-ticgn-cta-tva-toutes-les-taxes-sur-ma-facture/",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "nrel-degradation": {
    t: "Photovoltaic Degradation Rates: An Analytical Review (Jordan & Kurtz)",
    ed: "NREL",
    date: "2013",
    url: "https://research-hub.nrel.gov/en/publications/photovoltaic-degradation-rates-an-analytical-review-2/",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "kippzonen-pyranometre": {
    t: "Fiche du pyranomètre Kipp & Zonen CMP6",
    ed: "OTT HydroMet / Kipp & Zonen (fabricant)",
    date: null,
    url: "https://www.ott.com/products/cmp6-pyranometer",
    niveau: "secondaire",
    vu: "2026-10-06",
  },
  "pveducation-noct": {
    t: "Nominal Operating Cell Temperature",
    ed: "PVEducation.org",
    date: null,
    url: "https://www.pveducation.org/node/177",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "rex-transformateur-bourdonnement": {
    t: "Why Do Transformers Hum? Understanding the Buzzing Sound",
    ed: "Rex Power Magnetics (fabricant)",
    date: "17 août 2026",
    url: "https://www.rexpowermagnetics.com/?p=3426",
    niveau: "secondaire",
    vu: "2026-10-06",
  },
  "rte-be2025-consommation": {
    t: "Bilan électrique 2025 : consommation",
    ed: "RTE",
    date: "2026",
    url: "https://analysesetdonnees.rte-france.com/bilan-electrique-2025/consommation",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "rte-be2025-prix": {
    t: "Bilan électrique 2025 : prix (version anglaise)",
    ed: "RTE",
    date: "2026",
    url: "https://analysesetdonnees.rte-france.com/en/annual-review-2025/prices",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "rte-be2025-production": {
    t: "Bilan électrique 2025 : production",
    ed: "RTE",
    date: "2026",
    url: "https://analysesetdonnees.rte-france.com/bilan-electrique-2025/production",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "rte-be2025-rapport": {
    t: "Bilan électrique 2025 : rapport complet",
    ed: "RTE",
    date: "mars 2026",
    url: "https://assets.rte-france.com/prod/public/2026-03/Bilan-electrique-2025-rapport-complet_0.pdf",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "rte-be2025-synthese": {
    t: "Bilan électrique 2025 : synthèse (version anglaise)",
    ed: "RTE",
    date: "2026",
    url: "https://analysesetdonnees.rte-france.com/en/annual-review-2025/keyfindings",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "rte-interconnexions": {
    t: "Interconnections supporting an integrated European power system",
    ed: "RTE",
    date: null,
    url: "https://www.rte-france.com/en/basics-electricity/regulatory-framework/interconnections-supporting-integrated-european-power-system",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "reussir-patre-moutons": {
    t: "Des moutons sous les panneaux solaires",
    ed: "Réussir Pâtre (presse agricole)",
    date: "25 février 2020",
    url: "https://www.reussir.fr/patre/des-moutons-sous-les-panneaux-solaires-0",
    niveau: "secondaire",
    vu: "2026-10-06",
  },
  "sdes-chiffres-cles-2025": {
    t: "Chiffres clés de l’énergie, édition 2025 : méthodologie et définitions",
    ed: "SDES, ministère chargé de l’énergie",
    date: "2025",
    url: "https://www.statistiques.developpement-durable.gouv.fr/edition-numerique/chiffres-cles-energie/fr/20-methodologie---definitions",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "solartraders-module-430": {
    t: "Fiche du module LONGi LR5-54HTH-430M (430 Wc)",
    ed: "Solartraders (distributeur)",
    date: null,
    url: "https://www.solartraders.com/fr/products/module/longi-solar-lr5-54hth-430m-cre",
    niveau: "secondaire",
    vu: "2026-10-06",
  },
  "soren-rapport-2025": {
    t: "Rapport d’activité 2025",
    ed: "Soren",
    date: "6 juillet 2026",
    url: "https://www.soren.eco/rapport-dactivite-soren-2025/",
    niveau: "officiel",
    vu: "2026-10-06",
  },
  "utrecht-cameras-ciel": {
    t: "Benchmarking of solar irradiance nowcast performance derived from all-sky imagers (Logothetis et al.)",
    ed: "Université d’Utrecht",
    date: "2022",
    url: "https://research-portal.uu.nl/en/publications/benchmarking-of-solar-irradiance-nowcast-performance-derived-from/",
    niveau: "officiel",
    vu: "2026-10-06",
  },
};

/** Une source, prête à afficher : « Éditeur, Titre (date) ». */
export const libelleSource = (cle) => {
  const s = SOURCES[cle];
  return s ? `${s.ed}, ${s.t}${s.date ? ` (${s.date})` : ""}` : cle;
};

/** La date de consultation la plus récente du registre, en clair (« 6 octobre 2026 »). */
export const sourcesVuesLe = () => {
  const d = Object.values(SOURCES).map((s) => s.vu).sort().pop();
  return d ? new Date(d + "T12:00:00").toLocaleDateString("fr-FR", { day: "numeric", month: "long", year: "numeric" }) : "";
};
