/* Wattlings · jeu/recit/arenes/arene-6.js
   Arène 6 · Détecter — Arène de la Nuit : couleurs, champion (La Veilleuse), ses répliques, les trois dresseurs et leurs questions.
   Une question : Q("question", "bonne réponse", "explication", "mauvaise réponse 1", "pourquoi", "mauvaise réponse 2", "pourquoi"). */

const ARENE_6={id:6,badge:'Détecter',name:'Arène de la Nuit',champ:'La Veilleuse',theme:'nuit',col:'#5b6ee0',wall:'#eceefa',b:L.arena[6],
  cpal:{shirt:'#39426a',pants:'#1c2440',hair:'#ece6d6',style:'long',hat:'#1c2440',skin:'#6b4128',lash:1},
  cIntro:["Arène de la Nuit. Je vois tout ce qui consomme quand personne ne regarde.","Tu as fait ta ronde ? Alors chiffre-moi ce que coûtent ces dérives, et règle tes alertes."],
  cWin:["Tu sais ce qui fuit, combien ça coûte, et comment ne pas crier au loup. Voici le badge Détecter.","Le jour se lève sur Ampère-sur-Loire."],
  next:"Badge Détecter ! Maintenant qu'on sait où ça fuit, on agit. Demande en ville par où commencer, puis présente ton plan à l'Arène du Chantier.",
  tr:[
   {n:'Rondier Basile',pal:{shirt:'#2c2c34',pants:'#2c2c34',hair:'#5a3a22',hat:'#1c2440',skin:'#f1c7a1'},intro:"Qui va là ? … Ah. Un candidat. Lampe dans les yeux, question dans la foulée.",lose:"Tu vois clair, même dans le noir.",qs:[
    Q("Détecter une dérive, c'est comparer la consommation réelle à…","Ce qu'elle devrait être","On cherche l'écart au normal, puis on estime son coût.","La consommation du voisin","Le voisin n'a ni ton bâtiment ni tes horaires.","La facture du mois","La facture arrive trop tard et ne dit pas quand."),
    Q("Il est 2 h du matin, personne ne tire d'eau, et le compteur d'eau tourne. Conclusion ?","Il y a une fuite","Un bâtiment vide qui consomme plus que d'habitude, c'est pareil.","Le compteur est cassé","Possible, mais la fuite est bien plus probable.","Tout va bien","Un compteur qui tourne sans raison, ce n'est jamais « tout va bien ».")]},
   {n:'Guetteuse Nour',pal:{shirt:'#39426a',pants:'#1c2440',hair:'#2b1d14',skin:'#d19a6a',lash:1,hat:'#8a3b3b',hatType:'voile'},intro:"Je t'ai vu venir depuis l'entrée. Voyons si tu vois venir les dérives.",lose:"Rien ne t'échappe. Passe.",qs:[
    Q("Pourquoi une référence glissante (moyenne des dernières semaines) peut-elle masquer une dérive ?","Parce qu'après quelques semaines, la dérive fait partie de la référence","La référence « apprend » la nouvelle consommation : l'écart disparaît alors que le gaspillage continue.","Parce qu'elle ignore les week-ends","Ce n'est pas le problème principal.","Parce qu'elle est calculée en kW","L'unité n'y change rien."),
    Q("La chaudière consomme un samedi de juillet. Quel type d'alerte le repère le mieux ?","Une règle métier liée au calendrier","En été et le week-end, la chaudière ne devrait pas tourner : une règle simple suffit.","Un seuil de puissance électrique","La chaudière brûle du gaz.","Le montant de la facture annuelle","On le verrait un an trop tard.")]},
   {n:'Vigie Oscar',pal:{shirt:'#2c2c34',pants:'#39426a',hair:'#141216',style:'tresses',skin:'#9a6440'},intro:"Halte ! Dernier poste avant la Veilleuse. Mot de passe : une bonne réponse.",lose:"Mot de passe accepté.",qs:[
    Q("Lequel n'est PAS une dérive ?","Une pointe à midi un jour de classe","C'est le fonctionnement normal d'un bâtiment occupé.","Un talon qui monte de 6 à 9 kW","C'est la dérive la plus classique.","Le chauffage qui tourne en été","Celle-là aussi est un grand classique."),
    Q("Sans référence (baseline), on ne peut pas…","Détecter : il faut savoir ce qui est « normal »","Pour trouver l'anormal, on définit d'abord le normal.","Facturer","La facture n'a pas besoin de baseline.","Relever les compteurs","Le relevé se fait très bien sans."),
    Q("Une alerte se déclenche sur une donnée fausse. Qu'est-ce que ça montre ?","Que la détection dépend de l'étape Fiabiliser","Trop de fausses alertes, et plus personne ne les lit.","Que le bâtiment gaspille","La consommation réelle n'a pas bougé.","Qu'il faut plus d'alertes","Il en faut surtout de meilleures.")]}]};
